#!/usr/bin/env python3
"""Identité Titanio Vero appliquée aux réglages globaux de Shrine.

Les jetons de licence du thème (animations_type, fav_collection) sont repris
tels quels depuis la sauvegarde faite avant toute modification :
assets/originale-settings_data.json.txt sur le thème.
"""
import json

# ---- palette relevée sur le site de référence -----------------------------
NERO, NERO_2 = "#121212", "#1C1C1C"
BIANCO, ROSSO = "#FFFFFF", "#BF092F"

LICENCE_ANIMATIONS = (
    "pNf4GcTOAMWLEB2qdsrZtqX9NYIlRXV60QkUvhzwy7MLas HVYTgNsCAuFJqv9xZeRoKP3LfrnQskLwMEdypY8O7bGTZXtWAHaV2mUDcqFo5Kpi   "
    "FtuZdshCRKm57pgLvNIbjFoWaDH9ETyABrGoJQexzUXdVcTWlZ6l3sPqkN4OYRaJ   "
    "TOBrUtLY7KwRgpdiqEzPfHoV8NMeJ50Z9sXn3Ikv2RzDbwGa4LFJOz8XmSHuN7lY   "
    "qsxCmT7VFbhlz1enXaBGJ3muYUgNWoPKoE5vZ04FDxpyKh87nTjcIGrLQVaRpzDU   "
    "tbWYlQeVsknzPCoH90RXgYijZbBd1vFKc7OLJ3pga2TUmCzIoeXf68MQUV5NwHrW   "
    "i0KdvXzEmPtaBY5ZAhgrWQFcHlC1VEhRysXMv4nuOqSbZdGT7tjfNYeOkHpTAIqg   "
    "laVbjP9g2KoqmHeOYJixd8MRUN3EGutvcyQrAfowSk7WxzJF5nV12TpFHuBCW0Zr   "
    "SDqEpYbHW3gFT0Kz9XujmMXKvzAioGdt6RIQewslOa4cbNOp2LRMVT5pUCDkgzWf"
)
LICENCE_FAV = (
    "GGkLhoTOiV67l21Pb1r8JxbwGAkXLmer7YrABSJ9+A9EXpMu2rSrjF9lHa0vqrWGeeDHu7qtpr+mgxIPPKrM0ejIby9ZNuJF4dFk6amcBZ0j"
    "otWApqjdOhQIhMWQVZ0794EEN3Gp6q+hiFhBjWHj1+pTBR3xtiz1jODSHRCNTCGlXN7Iu8CDFs/VLut3g5H43vDSZMIwAJMurqV3IK5GOHTr"
    "H1NdIVG0H3QcA9//zSQlxswDRMsm5bamaw9MygihDMlZQ6QlPFSP2VFmaUrRhvwHgDWkOcFtLkvV1HQqnzdRA3AbzmzffCiXn1Gkd7DwMBp/"
    "kXuCvSCHt9TT0ZQbA5CyZBX5SXu5n3utfkf4ZEYF+ckSufFydtJWhrRuDGuKYruLRto9jNPdruIZvchs7Q=="
)

SWATCHES = ("Black = #000000,\nWhite = #FFFFFF,\nRed = #FF0000,\nBlue = #0000FF,\nGreen = #008000,\n"
            "Yellow = #FFFF00,\nOrange = #FFA500,\nPurple = #800080,\nPink = #FFC0CB,\nBrown = #A52A2A,\n"
            "Gray = #808080,\nNavy = #000080,\nTeal = #008080,\nMaroon = #800000,\nOlive = #808000,\n"
            "Lime = #00FF00,\nAqua = #00FFFF,\nSilver = #C0C0C0,\nGold = #FFD700,\nBeige = #F5F5DC,")

current = {
    "animations_type": LICENCE_ANIMATIONS,
    "disable_inspect": True,
    "country_list_function": "block",
    "country_list": "",
    "logo_width": 190,
    "mobile_logo_width": 130,
    # ---- couleurs : le passage en sombre est le levier le plus visible ----
    "colors_solid_button_labels": BIANCO,
    "colors_accent_1": ROSSO,
    "gradient_accent_1": "",
    "colors_accent_2": ROSSO,
    "gradient_accent_2": "",
    "colors_text": BIANCO,
    "colors_outline_button_labels": BIANCO,
    "colors_background_1": NERO,
    "gradient_background_1": "",
    "colors_background_2": NERO_2,
    "gradient_background_2": "",
    "type_header_font": "poppins_n7",
    "heading_scale": 120,
    "heading_letter_spacing": 0,
    "type_body_font": "harmonia_sans_n4",
    "body_scale": 100,
    "enable_rtl": False,
    "display_store_languages": False,
    "enable_load_animations": True,
    "repeat_section_animations": False,
    "badge_position": "top left",
    "badge_corner_radius": 8,
    "sale_badge_color_scheme": "accent-1",
    # aucune remise chiffrée : elle exigerait un prix de référence sur 30 jours
    "sale_badge_text": "OFFERTA",
    "sold_out_badge_color_scheme": "inverse",
    "slider_arrow_size": 30,
    "accent_icons": "text",
    "page_width": 1200,
    "spacing_sections": 0,
    "spacing_grid_horizontal": 40,
    "spacing_grid_vertical": 40,
    "link_btn_hover": "arrow",
    "action_btn_hover": "center",
    "buttons_border_thickness": 2,
    "buttons_border_opacity": 100,
    "buttons_radius": 10,
    "buttons_shadow_opacity": 0,
    "buttons_shadow_horizontal_offset": 0,
    "buttons_shadow_vertical_offset": 4,
    "buttons_shadow_blur": 5,
    "swatches_border_radius": 100,
    "swatches_border_opacity": 0,
    "swatches_selected_border_opacity": 50,
    "variant_pills_accent_color": "text",
    "variant_pills_bold_text": False,
    "variant_pills_border_thickness": 1,
    "variant_pills_border_opacity": 55,
    "variant_pills_radius": 10,
    "variant_pills_shadow_opacity": 0,
    "variant_pills_shadow_horizontal_offset": 0,
    "variant_pills_shadow_vertical_offset": 4,
    "variant_pills_shadow_blur": 5,
    "pickers_border_color": "text",
    "pickers_text_color": "text",
    "pickers_overlay_color": "accent-1",
    "pickers_overlay_opacity": 8,
    "pickers_border_thickness": 1,
    "pickers_border_opacity": 30,
    "pickers_radius": 10,
    "pickers_hover_overlay_opacity": 10,
    "pickers_hover_border_opacity": 55,
    "quantity_color_scheme": "background-1",
    "quantity_border_color": "text",
    "quantity_text_color": "text",
    "quantity_overlay_color": "accent-1",
    "quantity_overlay_opacity": 6,
    "quantity_border_thickness": 1,
    "quantity_border_opacity": 30,
    "quantity_radius": 10,
    "quantity_hover_overlay_opacity": 6,
    "inputs_border_thickness": 1,
    "inputs_border_opacity": 40,
    "inputs_radius": 10,
    "inputs_shadow_opacity": 0,
    "inputs_shadow_horizontal_offset": 0,
    "inputs_shadow_vertical_offset": 4,
    "inputs_shadow_blur": 5,
    "card_style": "card",
    "card_image_padding": 0,
    "card_text_alignment": "center",
    "card_color_scheme": "background-2",
    "product_cards_badge_push_sides": True,
    "product_cards_custom_badges_list": "PIÙ VENDUTO, SET COMPLETO, NOVITÀ",
    "card_border_thickness": 0,
    "card_border_opacity": 10,
    "card_corner_radius": 14,
    "card_shadow_opacity": 0,
    "card_shadow_horizontal_offset": 2,
    "card_shadow_vertical_offset": 6,
    "card_shadow_blur": 15,
    "collection_card_style": "card",
    "collection_card_image_padding": 0,
    "collection_card_text_alignment": "center",
    "collection_card_color_scheme": "background-2",
    "collection_card_border_thickness": 0,
    "collection_card_border_opacity": 10,
    "collection_card_corner_radius": 14,
    "collection_card_shadow_opacity": 0,
    "collection_card_shadow_horizontal_offset": 2,
    "collection_card_shadow_vertical_offset": 6,
    "collection_card_shadow_blur": 15,
    "blog_card_style": "card",
    "blog_card_image_padding": 0,
    "blog_card_text_alignment": "center",
    "blog_card_color_scheme": "background-2",
    "blog_card_border_thickness": 0,
    "blog_card_border_opacity": 10,
    "blog_card_corner_radius": 14,
    "blog_card_shadow_opacity": 0,
    "blog_card_shadow_horizontal_offset": 10,
    "blog_card_shadow_vertical_offset": 10,
    "blog_card_shadow_blur": 35,
    "text_boxes_border_thickness": 0,
    "text_boxes_border_opacity": 10,
    "text_boxes_radius": 16,
    "text_boxes_shadow_opacity": 0,
    "text_boxes_shadow_horizontal_offset": 10,
    "text_boxes_shadow_vertical_offset": 12,
    "text_boxes_shadow_blur": 20,
    "media_border_thickness": 0,
    "media_border_opacity": 10,
    "media_radius": 16,
    "media_shadow_opacity": 0,
    "media_shadow_horizontal_offset": 0,
    "media_shadow_vertical_offset": 0,
    "media_shadow_blur": 20,
    "popup_border_thickness": 1,
    "popup_border_opacity": 10,
    "popup_corner_radius": 14,
    "popup_shadow_opacity": 10,
    "popup_shadow_horizontal_offset": 10,
    "popup_shadow_vertical_offset": 12,
    "popup_shadow_blur": 20,
    "drawer_border_thickness": 1,
    "drawer_border_opacity": 10,
    "drawer_shadow_opacity": 0,
    "drawer_shadow_horizontal_offset": 0,
    "drawer_shadow_vertical_offset": 4,
    "drawer_shadow_blur": 5,
    "brand_headline": "",
    "brand_description": "",
    "brand_image_width": 100,
    "social_facebook_link": "",
    "social_instagram_link": "",
    "social_youtube_link": "",
    "social_tiktok_link": "",
    "social_twitter_link": "",
    "social_snapchat_link": "",
    "social_pinterest_link": "",
    "social_tumblr_link": "",
    "social_vimeo_link": "",
    "predictive_search_enabled": True,
    "predictive_search_show_vendor": False,
    "predictive_search_show_price": True,
    "currency_code_enabled": False,
    "scrollbar_style": "default",
    "scrollbar_thumb_color": "#555555",
    "scrollbar_width": 9,
    "cart_type": "drawer",
    "cart_icon": "bag_2",
    "show_vendor": False,
    "show_cart_note": False,
    "cart_drawer_collection": "",
    "swatches_predefined_colors": SWATCHES,
    "checkout_accent_color": ROSSO,
    "checkout_button_color": ROSSO,
    "fav_collection": LICENCE_FAV,
    "show_cart_payment_badges": True,
    "cart_trust_badges_width": 100,
    "enable_cart_discount": False,
    "enable_cart_timer": True,
    "cart_timer_text": "<strong>Carrello riservato per altri [timer] minuti!</strong>",
    "enable_cart_progress_bar": False,
    "cart_progress_message": "Aggiungi [amount] per la spedizione gratuita!",
    "cart_progress_success_message": "Spedizione gratuita sbloccata! 🎉",
    "cart_progress_icon": "local_shipping",
    "enable_cart_upsell_1": False,
    "cart_upsell_1_product": "",
    "cart_upsell_1_btn_label": "+ Aggiungi",
    "enable_cart_upsell_2": False,
    "cart_upsell_2_product": "",
    "cart_upsell_2_title": "",
    "cart_upsell_2_desc": "",
    "cart_upsell_2_btn_label": "+ Aggiungi",
    "section_animation_type": "none",
}
print("réglages globaux :", len(current), "clés")
json.dump(current, open("_current.json", "w", encoding="utf-8"), ensure_ascii=False)
